
services:
  api:
    image: api:latest
    container_name: api
    ports:
      - "8000:5000"
    env_file:
      - ./api/.env 
    networks:
      - medgraph-network
  frontend:
    image: front:latest
    container_name: frontend
    ports:
      - "8080:80"
    networks:
      - medgraph-network
    depends_on:
      - api

networks:
  medgraph-network:
    driver: bridge
  